export const GET_CATEGORIES_FROM_DB = 'GET_CATEGORIES_FROM_DB'
export const GET_SUBCATEGORIES_FROM_DB = 'GET_SUBCATEGORIES_FROM_DB'
export const GET_SKILLS_FROM_DB = 'GET_SKILLS_FROM_DB'
export const GET_PATHS_FROM_DB = 'GET_PATHS_FROM_DB'

export const SAGA_FETCH_CATEGORIES = 'SAGA_FETCH_CATEGORIES'
export const SAGA_FETCH_SUBCATEGORIES = 'SAGA_FETCH_SUBCATEGORIES'
export const SAGA_FETCH_SKILLS = 'SAGA_FETCH_SKILLS'
export const SAGA_FETCH_PATHS = 'SAGA_FETCH_PATHS'


export const CURRENT_CATEGORY = 'CURRENT_CATEGORY'
export const CURRENT_SUBCATEGORY = 'CURRENT_SUBCATEGORY'
export const CURRENT_SKILL = 'CURRENT_SKILL'
export const CURRENT_PATH = 'CURRENT_PATH'

export const DELETE_CURRENT_CATEGORY = 'DELETE_CURRENT_CATEGORY'
export const DELETE_CURRENT_SUBCATEGORY = 'DELETE_CURRENT_SUBCATEGORY'
export const DELETE_CURRENT_SKILL = 'DELETE_CURRENT_SKILL'
export const DELETE_CURRENT_PATH = 'DELETE_CURRENT_PATH'

export const CONSTRUCTOR_DAY_POPUP = 'CONSTRUCTOR_DAY_POPUP'
export const CHANGEBLE_DAY = 'CHANGEBLE_DAY'